module.exports.descriptors = [
    'Azul',
    'Francisco',
    'Senora',
    'Americano',
    'Globe Fund',
    'Memorial',
    'King One',
    'Kezar',
    'Monterey',
    'Great American',
    'Minute Man',
    'Civic',
    'Frontier',
    'Nathaniel',
    'Waterfront',
    'Dignity Life',
    'Speedland',
    'Golden Row',
    'Fulcrum',
    'Huskyville',
    'Century Life',
    'Hermosa',
    'Techmo',
    'Helix',
    'Vertex',
    'Beacon',
    'Gamma Fund',
    'Phantom',
    'Immortal',
    'Particle Tech',
    'Jubilee',
    'Red Marble',
    'Steve Young',
    'Jade',
    'Enclave',
    'Gracie Bank',
    'Aurelian',
    'Muse',
    'Serenity',
    'Crimsonton',
    'Alamo'
]

module.exports.places = [
    'Field',
    'Stadium',
    'Estadio',
    'Park',
    'Place',
    'Centre',
    'Center',
    'Coliseum',
    'Ballpark',
    'Superdome',
    'Sportsplex',
    'Arena',
    'Forum',
    'Garden',
    'Astrodome',
    'Grounds',
    'Bowl'
]

module.exports.teams = [
    'Warriors',
    'Rangers',
    'Heroes',
    'Kingfishers',
    'Falcons',
    'Pirates',
    'Pigeons',
    'Tigers',
    'Chargers',
    'Soldiers',
    'Wolverines',
    'Predators',
    'Earthquakes',
    'Wreckers',
    'Ogres',
    'Crunchers',
    'Stars',
    'Hedgehogs',
    'Stallions',
    'Vikings',
    'Bulldogs',
    'Gnomes',
    'Sabretooths',
    'Alligators',
    'Toucans',
    'Scorpions',
    'Hurricanes',
    'Bruisers',
    'Pelicans',
    'Roadrunners',
    'Sliders',
    'Crocodiles',
    'Mallards',
    'Blades',
    'Riders',
]

